name: TournoiArcherChest
m_weight: 15
m_name: Plastron archer de tournoi
m_description: Ce plastron doit être utilisée uniquement durant les tournois Valkream.
clonePrefabName: ArmorWarriorBMChest_TW
mockName: 
customIcon: 
material: TournoiArcherChest_mat
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack: 
Secondary_Attack: 
Damage: 
Damage_Per_Level: 
Armor:
  armor: 25
  armorPerLevel: 2
FoodStats: 
Moddifiers:
  m_movementModifier: -0.02
  m_EitrRegen: 0
  m_BaseItemStaminaModifier: 0
SE_Equip: 
SE_SET_Equip:
  SetName: Tournoi Archer Valkream
  Size: 3
  EffectName: SE_SetEffect_TournoiArcherArmor
ShieldStats:
  m_blockPower: 10
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 1.5
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: false
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: true
m_teleportable: false
m_backstabbonus: 4
m_knockback: 10
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 3000
m_durabilityPerLevel: 200
m_equipDuration: 2
m_skillType: Swords
m_animationState: OneHanded
m_itemType: Chest
m_toolTier: 0
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects: []
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect: []
  Trail_Effect: []
