Name: CapeCamelotEffect
Status_m_name: Cape des Seigneurs
Category: ''
IconName: 
ClonedSE:
CustomIcon: LogoLords64.png
FlashIcon: false
CooldownIcon: false
Tooltip: Cette cape offre une protection ad√©quate tout en style.
Attributes: None
StartMessageLoc: TopLeft
StartMessage: ''
StopMessageLoc: TopLeft
StopMessage: ''
RepeatMessageLoc: TopLeft
RepeatMessage: ''
RepeatInterval: 0
TimeToLive: 0
StartEffect_: 
StopEffect_: 
StartEffect_PLUS: []
StopEffect_PLUS: []
Cooldown: 0
ActivationAnimation: gpower
SeData:
  m_tickInterval: 0
  m_healthPerTickMinHealthPercentage: 0
  m_healthPerTick: 0
  m_healthOverTime: 0
  m_healthOverTimeDuration: 0
  m_healthOverTimeInterval: 0
  m_staminaOverTime: 0
  m_staminaOverTimeDuration: 0
  m_staminaDrainPerSec: 0
  m_runStaminaDrainModifier: -0.15
  m_jumpStaminaUseModifier: -0.15
  m_eitrOverTime: 0
  m_eitrOverTimeDuration: 0
  m_healthRegenMultiplier: 1
  m_staminaRegenMultiplier: 1
  m_eitrRegenMultiplier: 1
  m_raiseSkill: None
  m_raiseSkillModifier: 0
  m_skillLevel: None
  m_skillLevelModifier: 0
  m_skillLevel2: None
  m_skillLevelModifier2: 0
  m_mods: []
  m_modifyAttackSkill: None
  m_damageModifier: 1
  m_noiseModifier: 0
  m_stealthModifier: 0
  m_addMaxCarryWeight: 0
  m_speedModifier: 0.05
  m_maxMaxFallSpeed: 5
  m_fallDamageModifier: -1
  m_tickTimer: 0
  m_healthOverTimeTimer: 0
  m_healthOverTimeTicks: 0
  m_healthOverTimeTickHP: 0
